author: Golfing8
main: com.golfing8.kcommon.KCommon
version: 1.1
name: KCommon
api-version: 1.13
depend:
  - PlaceholderAPI
  - Vault
softdepend:
  - HolographicDisplays
  - DecentHolograms
  - ItemsAdder